[book]
authors = ["Kazi Rifat Morshed"]
language = "en"
multilingual = false
src = "src"
title = "Vitamin C Programming Supplement"

[output.html]
mathjax-support = true

[output.html.code.hidelines]
python = "~"
c = "~"
hint = "~"